### ISSUE TITLE
Migrating to react 18

### ISSUE THREAD

**Issue by fixer26rus** [fangpenlin/avataaars-generator#105]
Is there any plans to migrate to react 18?

**Comment by JacobDel** [comment]
nope, dead repo

**Comment by mariaSlimani** [comment]
Hey, I forked the repo and I'm trying to migrate to react 18. Did get it working but I'm still getting some legacy warnings here and there. Hopefully I'll get it working.

**Comment by JacobDel** [comment]
let me know if I can help

Would be nice if we could merge with original repo somehow

**Comment by JacobDel** [comment]
@mariaSlimani  I solved the legacy warning. I replaced the deprecated context with React.useContext. Works great for my application

React:https://github.com/JacobDel/avataaars
React native:https://github.com/JacobDel/react-native-avataaars

**Comment by mariaSlimani** [comment]
Hey @JacobDel ! first, thanks for taking the initiative! (if you saw the mess my commits were, you'd have figured I was having trouble with it XD).
I tested your code (installed the package into the react app i'm working on, using npm install JacobDel/avataaars) unfortunately i got this error (not warning): 
`react_1.default is undefined
./node_modules/avataaars/dist/options/OptionContext.js@http://192.168.1.34:3001/static/js/bundle.js:17336:1
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./node_modules/avataaars/dist/options/index.js@http://192.168.1.34:3001/static/js/bundle.js:17497:42
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./node_modules/avataaars/dist/avatar/top/accessories/index.js@http://192.168.1.34:3001/static/js/bundle.js:16316:36
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./node_modules/avataaars/dist/avatar/index.js@http://192.168.1.34:3001/static/js/bundle.js:10587:40
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./node_modules/avataaars/dist/index.js@http://192.168.1.34:3001/static/js/bundle.js:17036:35
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./src/components/RandomAvatar.js@http://192.168.1.34:3001/static/js/bundle.js:680:86
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./src/containers/Chatbot.js@http://192.168.1.34:3001/static/js/bundle.js:954:101
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./src/containers/LandingPage.js@http://192.168.1.34:3001/static/js/bundle.js:1349:85
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./src/containers/App.js@http://192.168.1.34:3001/static/js/bundle.js:851:89
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
fn@http://192.168.1.34:3001/static/js/bundle.js:101295:21
./src/index.js@http://192.168.1.34:3001/static/js/bundle.js:1533:92
options.factory@http://192.168.1.34:3001/static/js/bundle.js:101638:31
__webpack_require__@http://192.168.1.34:3001/static/js/bundle.js:101056:33
@http://192.168.1.34:3001/static/js/bundle.js:102284:56
@http://192.168.1.34:3001/static/js/bundle.js:102286:12`

My app works normally when i install my version using npm install mariaSlimani/avataaars (if we were to ignore the warnings that is).

**Comment by JacobDel** [comment]
I forgot to build it to the dest folder (was testing it with src files). Does it work now?
btw we have a conflicting yarn version. It might help if you delete the yarn.lock file and run `yarn install`

**Comment by mariaSlimani** [comment]
Now when i install it I get : 
`OptionContext.js:124 Uncaught TypeError: Cannot read properties of undefined (reading 'createContext')
    at ./node_modules/avataaars/dist/options/OptionContext.js (OptionContext.js:124:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/avataaars/dist/options/index.js (index.js:7:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/avataaars/dist/avatar/top/accessories/index.js (index.js:26:1)
    at options.factory (react refresh:6:1)`

**Comment by JacobDel** [comment]
I found the issue, I'm working on it

**Comment by JacobDel** [comment]
should be fixed @mariaSlimani

**Comment by mariaSlimani** [comment]
Unfortunately not. Here's the error : 

![image](https://github.com/fangpenlin/avataaars-generator/assets/76159247/acaafaf9-0a2d-481a-a336-79d32413c6a7)

+ It just kept going (notice the number of errors at the top (it just kept on increasing).

**Comment by JacobDel** [comment]
Is it fixed now @mariaSlimani ?
